language: bash

sudo: false

addons:
  apt:
    sources:
      - debian-sid

before-script:
  - "sudo apt-get install cabal-install"
  - "cabal update"
  - "cabal install shellcheck"

script:
 - bash -c 'shopt -s globstar; shellcheck install.sh'
 - bash -c 'shopt -s globstar; shellcheck SOURCES/rbdef'
 - bash -c 'shopt -s globstar; shellcheck SOURCES/rbbuild SOURCES/blds/*'

matrix:
  fast_finish: true
